package io.tempokv.protocol.sql;

import java_cup.runtime.Symbol;

/**
 * Converts TempoKV SQL text into positioned Java CUP symbols.
 *
 * <p>This class is generated by JFlex during the build.</p>
 */
%%

%public
%final
%class TempoLexer
%unicode
%cup
%line
%column
%caseless

%{
    private Symbol symbol(int type) {
        return new Symbol(type, yyline + 1, yycolumn + 1, yytext());
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline + 1, yycolumn + 1, value);
    }

    private String stringValue() {
        return yytext().substring(1, yylength() - 1).replace("''", "'");
    }
%}

%eofval{
    return symbol(SqlSymbols.EOF);
%eofval}

Identifier = [A-Za-z_][A-Za-z0-9_]*
Integer = 0|[1-9][0-9]*
SqlString = \'([^\'\r\n]|\'\')*\'
Whitespace = [ \t\f\r\n]+
LineComment = "--"[^\r\n]*

%%

{Whitespace}       { /* ignored */ }
{LineComment}      { /* ignored */ }

"SELECT"           { return symbol(SqlSymbols.SELECT); }
"FROM"             { return symbol(SqlSymbols.FROM); }
"WHERE"            { return symbol(SqlSymbols.WHERE); }
"UPSERT"           { return symbol(SqlSymbols.UPSERT); }
"INTO"             { return symbol(SqlSymbols.INTO); }
"VALUES"           { return symbol(SqlSymbols.VALUES); }
"DELETE"           { return symbol(SqlSymbols.DELETE); }
"AS"               { return symbol(SqlSymbols.AS); }
"OF"               { return symbol(SqlSymbols.OF); }
"HISTORY"          { return symbol(SqlSymbols.HISTORY); }
"DIFF"             { return symbol(SqlSymbols.DIFF); }
"RESTORE"          { return symbol(SqlSymbols.RESTORE); }
"TO"               { return symbol(SqlSymbols.TO); }
"BETWEEN"          { return symbol(SqlSymbols.BETWEEN); }
"AND"              { return symbol(SqlSymbols.AND); }
"ORDER"            { return symbol(SqlSymbols.ORDER); }
"BY"               { return symbol(SqlSymbols.BY); }
"LIMIT"            { return symbol(SqlSymbols.LIMIT); }
"OFFSET"           { return symbol(SqlSymbols.OFFSET); }
"ASC"              { return symbol(SqlSymbols.ASC); }
"DESC"             { return symbol(SqlSymbols.DESC); }
"BEGIN"            { return symbol(SqlSymbols.BEGIN); }
"COMMIT"           { return symbol(SqlSymbols.COMMIT); }
"ROLLBACK"         { return symbol(SqlSymbols.ROLLBACK); }
"VERSION"          { return symbol(SqlSymbols.VERSION); }
"TIMESTAMP"        { return symbol(SqlSymbols.TIMESTAMP); }
"KEY"              { return symbol(SqlSymbols.KEY); }
"VALUE"            { return symbol(SqlSymbols.VALUE); }
"STATE"            { return symbol(SqlSymbols.STATE); }
"COMMITTED_AT"     { return symbol(SqlSymbols.COMMITTED_AT); }

"("                { return symbol(SqlSymbols.LPAREN); }
")"                { return symbol(SqlSymbols.RPAREN); }
","                { return symbol(SqlSymbols.COMMA); }
";"                { return symbol(SqlSymbols.SEMICOLON); }
"*"                { return symbol(SqlSymbols.STAR); }
"="                { return symbol(SqlSymbols.EQ); }
">="               { return symbol(SqlSymbols.GTE); }

{SqlString}        { return symbol(SqlSymbols.STRING, stringValue()); }
{Integer}          {
                       try {
                           return symbol(SqlSymbols.INTEGER, Long.parseLong(yytext()));
                       } catch (NumberFormatException exception) {
                           throw new SqlException(
                               SqlException.Kind.LEXICAL,
                               "integer literal is out of range",
                               yyline + 1,
                               yycolumn + 1);
                       }
                   }
{Identifier}       { return symbol(SqlSymbols.IDENT, yytext()); }

[^]                {
                       throw new SqlException(
                           SqlException.Kind.LEXICAL,
                           "unexpected character '" + yytext() + "'",
                           yyline + 1,
                           yycolumn + 1);
                   }
